name: Build Deb Package

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          brew install ldid dpkg
          
          # 1. 克隆 Theos 本体
          git clone https://github.com/theos/theos.git ~/theos
          
          # 2. 自动拉取和安装 missing 的 vendor/include 和 vendor/lib 等依赖
          export THEOS=~/theos
          $THEOS/bin/update-theos
          
          # 3. 清理并下载 iOS SDK
          rm -rf ~/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git ~/theos/sdks

      - name: Build Tweak
        run: |
          export THEOS=~/theos
          make package THEOS_PACKAGE_SCHEME=rootless GO_EASY_ON_ME=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RemoveWidgetBackground-deb
          path: packages/*.deb
