name: Build Deb Package

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          brew install ldid
          git clone --recursive https://github.com/theos/theos.git ~/theos
          # 先清理 Theos 自带的空 sdks 目录，避免致命冲突
          rm -rf ~/theos/sdks
          git clone --depth=1 https://github.com/hexedtext/SDKS.git ~/theos/sdks

      - name: Build Tweak
        run: |
          export THEOS=~/theos
          $THEOS/bin/make package THEOS_PACKAGE_SCHEME=rootless GO_EASY_ON_ME=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RemoveWidgetBackground-deb
          path: packages/*.deb
